version: "3.4"

services:
  oneauthserver:
    image: oneauthserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8015:8015
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
